---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu-jb
    image: jnbutters/ubuntu-jb
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    capabilities:
      - SYS_ADMIN
    privileged: true
    pre_build_image: true